name: Racket Coverage

on:
  push:
    branches:
      - "*"
    paths:
      - "**coverage.yml"
      - "**.rkt"
      - "**.scrbl"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.rkt"
      - "**.scrbl"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: test-env
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: "x64"
          distribution: "full"
          variant: "CS"
          version: "stable"
          packages: "cover, cover-coveralls"
      - run: raco pkg install --auto --skip-installed
      - run: |
          xvfb-run -a raco test .
          raco cover -b -f coveralls .
